/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BasicInput: typeof import('./src/components/calculator/views/input/BasicInput.vue')['default']
    Blank: typeof import('./src/components/calculator/tests/blank.vue')['default']
    DebugSwitcher: typeof import('./src/components/DebugSwitcher.vue')['default']
    Entry: typeof import('./src/components/calculator/views/input/Entry.vue')['default']
    ExtendedInput: typeof import('./src/components/calculator/views/input/ExtendedInput.vue')['default']
    FieldInput: typeof import('./src/components/calculator/input/FieldInput.vue')['default']
    FieldInputTest: typeof import('./src/components/calculator/tests/FieldInputTest.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Help: typeof import('./src/components/calculator/input/help.vue')['default']
    InputSummary: typeof import('./src/components/calculator/views/input/InputSummary.vue')['default']
    NumberInput: typeof import('./src/components/calculator/input/NumberInput.vue')['default']
    Projectile: typeof import('./src/components/calculator/views/input/Projectile.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
