<template>
<div class="flex_row_center_top">

<div class="flex_col_top_left" style="max-width: 900px;">
    <h1>{{ $t("articles.articles") }}</h1>
  <div class="article_full_reference" v-for="(publ, i) in publicationsLocal" :key="i">
        <span class="article_full_reference__authors">{{publ.authors}}</span>
        <span class="article_full_reference__year">{{publ.year}}</span>
        <span class="article_full_reference__title">{{publ.title}}</span>
        <span class="article_full_reference__journal">{{publ.journal}}</span>
        <span class="article_full_reference__volume_number_pages">{{publ.vol_number_pages}}</span>
    </div>

    <br/><br/><br/><br/><br/><br/><br/><br/>
    <h1>new way</h1>
    <div class="article_full_reference" v-for="(publ, i) in publications" :key="i">
        {{ publ.to_short_link_output() }}<br/>
        {{ publ.to_long_styled_output() }}<br/><br/>
    </div>
    {{ publications }}
</div>
</div> 
</template>

<script lang="ts" setup>

import { publications } from "@/model/articles"
const msg = 'Hello!'

// functions
function log() {
  console.log(msg)
}

class Publication {
    constructor(authors?: string,
    year?: string,
    title?: string,
    journal?: string,
    vol_number_pages?: string)
    {
        this.authors = authors;
        this.year = year;
        this.title = title;
        this.journal = journal;
        this.vol_number_pages = vol_number_pages;
    }
    authors?: string;
    year?: string;
    title?: string;
    journal?: string;
    vol_number_pages?: string;
}

const publicationsLocal: Publication[] = [
new Publication("Artemieva, N. A.; Shuvalov, V. V.", "2016.", "From Tunguska to Chelyabinsk via Jupiter ", "Annual Review of Earth and Planetary Sciences ", "44, 37-56"),
new Publication("Shuvalov, V. V.; Artemieva, N. A.; Glazachev, D. O.; Popova, O. P.; Svettsov, V. V.", "2016.", "Numerical Model of an Apophis-Like Impact Against The Earth", "79th Annual Meeting of the Meteoritical Society, held 7-12 August, 2016 in Berlin, Germany", "LPI Contribution No. 1921, id.6087"),
new Publication("Shuvalov, V. V.; Svettsov, V. V.; Artem'eva, N. A.; Trubetskaya, I. A.; Popova,O. P.; Glazachev, D. O.", "2017.", "Asteroid Apophis: Evaluating the Impact Hazards of such Bodies", "Solar System Research", "51(1), 44-58"),  
new Publication("Artemieva, N.A.; Shuvalov, V.V.; Svetssov, V.V.", "2017.", "Airbursts: We Will Shock You!", "80th Annual Meeting of the Meteoritical Society, held July 23-28, 2017 in Santa Fe, New Mexico", "LPI Contribution No., 1987, id.6041"),  
new Publication("Popova, O. P.; Glazachev, D. O.; Podobnaya, E. D.; Svetsov, V. V.; Shuvalov, V. V.", "2017.", "Radiation of Large Meteoroids Decelerated in the Earth's Atmosphere ", "80th Annual Meeting of the Meteoritical Society, held July 23-28, 2017 in Santa Fe, New Mexico", "LPI Contribution No., 1987, id.6376"),  
new Publication("Svetsov, V.V.; Artemieva, N.A.; Shuvalov, V.V.", "2017.", "Seismic Efficiency of Meteor Airbursts", "Doklady Earth Sciences", "475(2), 935-938"),  
new Publication("Svetsov, V.V.; Shuvalov, V. V.", "2017.", "Effects Of Thermal Radiation From Impact Plumes", "80th Annual Meeting of the Meteoritical Society, held July 23-28, 2017 in Santa Fe, New Mexico", "LPI Contribution No., 1987, id.6132"),  
new Publication("Shuvalov V. V.; Svetsov, V. V.; Popova, O. P.; Glazachev D. O.", "2017.", "Numerical Model Of The Chelyabinsk Meteoroid As A Strengthless Object ", "Planetary and Space Science", "147, 38-47"), 
new Publication("Shuvalov V. V.; Khazins, V.M.", "2017.", " Ionospheric Disturbances Initiated by Explosive Disruption of Chelyabinsk and Tunguska Cosmic Bodies", "80th Annual Meeting of the Meteoritical Society, held July 23-28, 2017 in Santa Fe, New Mexico", "LPI Contribution No., 1987, id.6044"),  
new Publication("Shuvalov, V. V.; Khazins, V.M.", "2018.", "Numerical Simulation of Ionospheric Disturbances Generated by the Chelyabinsk and Tunguska Space Body Impacts ", "Solar System Research", "52(2), 129-138"), 
new Publication("Svetsov, V. V.; Shuvalov, V. V.; Popova, O. P.", "2018.", "Radiation from a Superbolide", "Solar System Research", "52(3), 195-205"),  
new Publication("Glazachev, D. O.; Podobnaya, E. D.; Popova, O. P.; Artemieva, N. A.; Shuvalov, V. V.", "2018.", "Scaling Relations for Shock Wave Effects from Large Meteoroids Decelerated In The Earth's Atmosphere", "81st Annual Meeting of the Meteoritical Society, held 22-27 July 2018 in Moscow, Russia", "LPI Contribution No. 2067, id.6032"),  
new Publication("Kartashova, A. P.; Popova, O. P.; Glazachev, D. O.; Jenniskens, P.; Emel'yanenko, V. V.; Podobnaya, E. D.; Skripnik, A. Ya.", "2018.", "Study of Injuries from the Chelyabinsk Airburst Event", "Planetary and Space Science", "160, 107-114"),  
new Publication("Kartashova, A. P.; Popova, O. P.; Glazachev, D. O.; Jenniskens, P.; Podobnaya, E. D.", "2018.", "Eyewitness Accounts and Modeling Results for Chelyabinsk Airburst", "81st Annual Meeting of the Meteoritical Society, held 22-27 July 2018 in Moscow, Russia", "LPI Contribution No. 2067, id.6169"),  
new Publication("Naroenkov, S. A.; Glazachev, D. O.; Kartashova, A. P.; Popova, O. P.", "2018.", "The Constructor of Orbits for the Impact Effect Calculator", "81st Annual Meeting of the Meteoritical Society, held 22-27 July 2018 in Moscow, Russia", "LPI Contribution No. 2067, id.6317"),  
new Publication("Naroenkov, S. A.; Glazachev, D. O.; Kartashova, A. P.; Popova, O. P.; Turuntaev, I. S.", "2018.", "The Impact Effect Callculator of Celestial Body Impacts to the Earth: The Constructor of Hazardous Orbits", "Solar System Research", "52(6), 534-546"),  
new Publication("Podobnaya, E. D.; Glazachev, D. O.; Popova, O. P.; Svetsov, V. V.; Shuvalov V. V.", "2018.", " Scaling Relations for Radiation Effects due to Impacts of Large Cosmic Objects", "81st Annual Meeting of the Meteoritical Society, held 22-27 July 2018 in Moscow, Russia", "LPI Contribution No. 2067, id.6030"),  
new Publication("Svetsov, V.V.; Shuvalov, V. V.", "2018.", "Thermal Radiation and Luminous Efficiency of Superbolides", "Earth and Planetary Science Letters", "503, 10-16"),  
new Publication("Svetsov V. V.; Shuvalov V. V.; Artemieva N. A.; Khazins, V. M.; Popova, O. P.; Glazachev D. O.; Podobnaya, E. D.", "2018.", "Complex Assessment of Hazardous Effects of Impacts of Cosmic Objects", "81st Annual Meeting of the Meteoritical Society, held 22-27 July 2018 in Moscow, Russia", "LPI Contribution No. 2067, id.6145"),  
new Publication("Khazins, V.M.; Shuvalov, V. V.; Svettsov, V. V.", "2018.", "The Seismic Efficiency of Space Body Impacts ", "Solar System Research", "52(6), 547-556"),  
new Publication("Shuvalov, V. V.; Khazins, V.M.; Svettsov, V. V.", "2018.", "Estimation of Seismic Efficiency of Impacts of Cosmic Objects by Methods of Numerical Analysis", "81st Annual Meeting of the Meteoritical Society, held 22-27 July 2018 in Moscow, Russia", "LPI Contribution No. 2067, id.6068"),  
new Publication("Artemieva, N. A.; Shuvalov, V. V.", "2019.", "Atmospheric Shock Waves after Impacts of Cosmic Bodies up to 1000 m in Diameter", "Meteoritics and Planetary Science", "54(3), 592-608"),  
new Publication("Svetsov, V.V.; Shuvalov, V. V.", "2019.", "Thermal Radiation from Impact Plumes", "Meteoritics and Planetary Science", "54(1), 126-141")
    ]

//     get locale(): string {return this.$i18n.locale; }
//     set locale(val: string) {this.$i18n.locale = val;}
// }


</script>

<style scoped lang="scss">
  .article_full_reference{
        margin-top: 15px;
        margin-bottom: 15px;
    }
    //.article_full_reference__authors{

    //}
    .article_full_reference__year::before{
        content:" (";
    }
    .article_full_reference__year::after{
        content:") ";
    }
    .article_full_reference__title::after{
        content:"// ";
    }
    .article_full_reference__journal{
        font-style: italic;
    }
    .article_full_reference__journal::after{
        content:". ";
    }
    .article_full_reference__volume_number_pages::after{
        content:". ";

    }
  
</style>